services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: servify-backend
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - servify-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000/api/v1
    container_name: servify-frontend
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - servify-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: servify-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./SQLfiles:/docker-entrypoint-initdb.d
    networks:
      - servify-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U servify -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  servify-network:
    driver: bridge
